services:
  frontend:
    image: younghwancha/uavlogviewer
    build: .
    container_name: uav-frontend
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_CESIUM_TOKEN=${VUE_APP_CESIUM_TOKEN}

  backend:
    image: younghwancha/uavlogviewer-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: uav-backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  redis-data: 